"""Unit tests for turnmanager.py."""

import unittest
from .turnmanager import *

class TestExtractChoice(unittest.TestCase):
    def test_extract_choice(self):

        # Straightforward cases generated by Gemini
        options = ["Abstain", "Town", "Mafia"]
        self.assertEqual(extract_choice("Town", options), "Town")
        self.assertEqual(extract_choice("I abstain", options), "Abstain")
        self.assertEqual(extract_choice("I choose mafia", options), "Mafia")
        self.assertIsNone(extract_choice("MY HEAD IS FULL OF BEES", options))

        # Find names that are substrings of other names
        options = ["John", "Johnette", "Johnette Napolitano"]
        self.assertEqual(extract_choice("Johnette Napolitano", options), "Johnette Napolitano")
        self.assertEqual(extract_choice("I am voting for Johnette", options), "Johnette")
        self.assertEqual(extract_choice("john owes me fifty bucks its him", options), "John")

if __name__ == "__main__":
    unittest.main()
