"""Unit tests for turnmanager.py."""

import unittest
from .turnmanager import *

class TestExtractChoice(unittest.TestCase):
    def test_extract_choice(self):

        # Straightforward cases generated by Gemini
        options = ["Abstain", "Town", "Mafia"]
        self.assertEqual(extract_choice("Town", options), "Town")
        self.assertEqual(extract_choice("I abstain", options), "Abstain")
        self.assertEqual(extract_choice("I choose mafia", options), "Mafia")
        self.assertIsNone(extract_choice("MY HEAD IS FULL OF BEES", options))

        # Find names that are substrings of other names
        options = ["John", "Johnette", "Johnette Napolitano"]
        self.assertEqual(extract_choice("Johnette Napolitano", options), "Johnette Napolitano")
        self.assertEqual(extract_choice("I am voting for Johnette", options), "Johnette")
        self.assertEqual(extract_choice("john owes me fifty bucks its him", options), "John")

        # Check late overlaps
        options = ["John", "Bob", "John Bob"]
        self.assertEqual(extract_choice("John Bob", options), "John Bob")
        self.assertEqual(extract_choice("I am voting for John", options), "John")
        self.assertEqual(extract_choice("john owes me fifty bucks its him", options), "John")

        # Weird partial overlap cases
        options = ["Banana", "Nanana", "Nan", "Anan"]
        self.assertEqual(extract_choice("Banana", options), "Banana")
        self.assertEqual(extract_choice("Nanana", options), "Nanana")
        self.assertEqual(extract_choice("Nan", options), "Nan")
        self.assertEqual(extract_choice("Anan", options), "Anan")
        self.assertEqual(extract_choice("Bananana", options), "Nanana")
        self.assertEqual(extract_choice("Banananan", options), "Anan")
        self.assertEqual(extract_choice("Banananabananbana", options), "Ana")

if __name__ == "__main__":
    unittest.main()
